name: pytest

on:
    pull_request:
    push:
        branches: [master]

jobs:
    pytest:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -   uses: actions/setup-python@v2
        -   uses: py-actions/py-dependency-install@v2
        -   name: Run test suite
            run: pytest -vvv tests
